# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14c570c6e8c0dc0519393c6727dc0e98df4ba0820ca4e570542bb9787f9cd43d9cefb53de3f567bbb54bcdc76bd0676cca8f01fc8d6c1eece3671892041be453

test:
  secret_key_base: 68f7f098e97f38e0307adb978f8c13322f17f9ab0d58615fe08bf5dfad508014673985a9510709ba2058bfe522526a448609ac978f8163775fff5dc83ee1e6bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
